export { Background } from './Background';
export { Effects } from './Effects';
export { Footer } from './Footer';
export { Header } from './Header';
export { Image } from './Image';
export { Logo } from './Logo';
export { Menu } from './Menu';
export { SEO } from './SEO';
export { SocialMedia } from './SocialMedia';
